version: 2.1

jobs:
  build:
    docker:
      - image: debian:bookworm
    resource_class: large
    environment:
      LINUX_VER: 5.15.0-3-arm64-unsigned
    steps:
      - checkout
      - run: bash prepare.sh
      - run: bash build.sh
      - store_artifacts:
          path: /root/deb_artifacts

workflows:
  everything:
    jobs:
      - build
