version: 2.1

jobs:
  build-kernel:
    docker:
      - image: alpine:edge
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "ls"

workflows:
  everything:
    jobs:
      - build-kernel
