version: 2.1

jobs:
  build-kernel:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run
        command: 'ls'
      - run
        command: 'docker -v'

workflows:
  everything:
    jobs:
      - build-kernel
